### PR TITLE
Attempt at windows build

### PR DESCRIPTION
**Pull request by duncanmmacleod**
Checklist
* [x] Used a fork of the feedstock to propose changes
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/conda_smithy.html#how-to-re-render ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by isuruf** [comment]
@conda-forge-admin, please rerender

**Comment by isuruf** [comment]
I have a question. Why is this recipe having outputs, when there is only one output?

**Comment by duncanmmacleod** [comment]
@isuruf, this package supports building SWIG bindings for many languages, but we are starting with Python. I wrote it to use `outputs` to make adding in more language bindings easier in the future. Does that make sense?

**Comment by duncanmmacleod** [comment]
It's not, at least, its not supposed to be. Can you point me where you see that?

**Pull request closed without merging**
